// app/api/portal-invite/route.js
// Sends a portal invite to a tenant via Resend
// Creates an invite record in Supabase with a unique token

import { getSettings, emailWrap, fromAddress } from "@/lib/getSettings";

const SUPA_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPA_KEY = process.env.SUPABASE_ANON_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

async function supaInsert(table, data) {
  const r = await fetch(`${SUPA_URL}/rest/v1/${table}`, {
    method: "POST",
    headers: {
      apikey: SUPA_KEY,
      Authorization: `Bearer ${SUPA_KEY}`,
      "Content-Type": "application/json",
      Prefer: "return=representation",
    },
    body: JSON.stringify(data),
  });
  return r.json();
}

async function supaQuery(table, query) {
  const r = await fetch(`${SUPA_URL}/rest/v1/${table}?${query}`, {
    headers: { apikey: SUPA_KEY, Authorization: `Bearer ${SUPA_KEY}` },
  });
  return r.json();
}

export async function POST(request) {
  try {
    const body = await request.json();
    const { tenantName, tenantEmail, tenantId, pmId, roomId, propertyName, roomName, rent, moveIn } = body;

    if (!tenantEmail || !tenantName) {
      return Response.json({ ok: false, error: "Missing tenant name or email" }, { status: 400 });
    }

    const resendKey = process.env.RESEND_API_KEY;
    if (!resendKey) return Response.json({ ok: false, error: "RESEND_API_KEY not configured" }, { status: 500 });

    const s = await getSettings();

    // Get PM account id
    let pmAccountId = pmId;
    if (!pmAccountId) {
      const pms = await supaQuery("pm_accounts", `email=eq.${encodeURIComponent(s.email)}&select=id`);
      pmAccountId = pms?.[0]?.id;
    }

    // Create or find tenant record in relational table
    let tenantRecord = null;
    if (tenantId) {
      // Already have a tenants table row id
      tenantRecord = { id: tenantId };
    } else {
      // Check if tenant exists by email
      const existing = await supaQuery("tenants", `email=eq.${encodeURIComponent(tenantEmail)}&pm_id=eq.${pmAccountId}&select=id`);
      if (existing?.[0]) {
        tenantRecord = existing[0];
      } else {
        // Create tenant record
        const created = await supaInsert("tenants", {
          pm_id: pmAccountId,
          name: tenantName,
          email: tenantEmail,
          room_id: roomId || null,
          status: "active",
        });
        tenantRecord = created?.[0];
      }
    }

    // Invalidate any existing unused invites for this email
    await fetch(`${SUPA_URL}/rest/v1/invites?email=eq.${encodeURIComponent(tenantEmail)}&accepted_at=is.null`, {
      method: "DELETE",
      headers: { apikey: SUPA_KEY, Authorization: `Bearer ${SUPA_KEY}` },
    });

    // Create invite record — token auto-generated by Supabase default
    const inviteRows = await supaInsert("invites", {
      pm_id: pmAccountId,
      tenant_id: tenantRecord?.id || null,
      email: tenantEmail,
    });
    const invite = inviteRows?.[0];
    if (!invite?.token) {
      return Response.json({ ok: false, error: "Failed to create invite record" }, { status: 500 });
    }

    const portalUrl = `${s.siteUrl}/portal?token=${invite.token}`;
    const firstName = tenantName.split(" ")[0];

    // Send invite email
    await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: { Authorization: `Bearer ${resendKey}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        from: fromAddress(s),
        to: tenantEmail,
        subject: `Your tenant portal is ready — ${s.companyName}`,
        html: emailWrap(`
          <div style="text-align:center;margin-bottom:28px;">
            <h2 style="font-size:24px;margin:0 0 8px;color:#1a1714;">Welcome to your portal, ${firstName}!</h2>
            <p style="font-size:14px;color:#5c4a3a;margin:0;">View your lease, track payments, and submit maintenance requests — all in one place.</p>
          </div>

          <div style="background:#f0faf4;border:1px solid #c3e6cb;border-radius:10px;padding:20px;margin-bottom:20px;">
            <div style="font-size:11px;font-weight:700;color:#2d6a3f;text-transform:uppercase;letter-spacing:1px;margin-bottom:14px;">Your Details</div>
            <table style="width:100%;border-collapse:collapse;font-size:13px;">
              ${propertyName ? `<tr><td style="padding:6px 0;color:#5c4a3a;border-bottom:1px solid rgba(0,0,0,.06);">Property</td><td style="padding:6px 0;font-weight:700;text-align:right;border-bottom:1px solid rgba(0,0,0,.06);">${propertyName}</td></tr>` : ""}
              ${roomName ? `<tr><td style="padding:6px 0;color:#5c4a3a;border-bottom:1px solid rgba(0,0,0,.06);">Room</td><td style="padding:6px 0;font-weight:700;text-align:right;border-bottom:1px solid rgba(0,0,0,.06);">${roomName}</td></tr>` : ""}
              ${rent ? `<tr><td style="padding:6px 0;color:#5c4a3a;border-bottom:1px solid rgba(0,0,0,.06);">Monthly Rent</td><td style="padding:6px 0;font-weight:700;text-align:right;color:#2d6a3f;border-bottom:1px solid rgba(0,0,0,.06);">$${Number(rent).toLocaleString()}/mo</td></tr>` : ""}
              ${moveIn ? `<tr><td style="padding:6px 0;color:#5c4a3a;">Move-in</td><td style="padding:6px 0;font-weight:700;text-align:right;">${moveIn}</td></tr>` : ""}
            </table>
          </div>

          <div style="text-align:center;margin:28px 0;">
            <a href="${portalUrl}" style="display:inline-block;background:#d4a853;color:#1a1714;padding:16px 40px;border-radius:10px;font-weight:800;font-size:16px;text-decoration:none;">Access Your Portal →</a>
            <div style="font-size:11px;color:#999;margin-top:10px;">This link expires in 48 hours</div>
          </div>

          <div style="background:#f5f0e8;border-radius:10px;padding:18px;margin-bottom:20px;">
            <div style="font-size:11px;font-weight:700;color:#9a7422;text-transform:uppercase;letter-spacing:1px;margin-bottom:10px;">Sign in with</div>
            <div style="font-size:13px;color:#5c4a3a;line-height:1.8;">
              • Your Google account (recommended — one click)<br/>
              • Or create an account with your email and password<br/>
              • Use the same email address this invitation was sent to
            </div>
          </div>

          <p style="font-size:13px;color:#5c4a3a;">Questions? Reply to this email or call <strong>${s.phone}</strong>.</p>
        `, s),
      }),
    });

    return Response.json({ ok: true, token: invite.token, portalUrl });
  } catch (err) {
    console.error("Portal invite error:", err);
    return Response.json({ ok: false, error: String(err) }, { status: 500 });
  }
}
